Lab5
martynovappolina/IU5-Frontend-2021 pull request #10
Opened 2021-03-26 23:39 UTC by martynovappolina

2021-03-30 18:49 UTC, youraavdeev requested changes

2021-03-30 18:49 UTC, youraavdeev commented on lab4/5.js
> +module.exports = checkBrackets;
зачем во всех файлах еще по одному экспорту
зачем трогала 4 лабу?

2021-03-30 18:49 UTC, youraavdeev commented on lab5/1.js
> +    let new_arr = [];
нужно через reduce это ж в условии

2021-03-30 18:49 UTC, youraavdeev commented on lab5/1.js
> +// this.forEach(element => {
зачем это

2021-03-30 18:49 UTC, youraavdeev commented on lab5/4.js
> +// let cache = {};
зачем это все

2021-04-01 17:03 UTC, Crusader727 approved these changes
вливай

2021-04-04 09:42 UTC, merged